version: '3.9'

services:
  todo_core:
    volumes:
      - .:/app/src/
    environment:
      TODO_CORE_DEBUG: "True"

  comments:
    build:
      target: dev
    environment:
      # Enables autoreload.
      COMMENTS_RELOAD: "True"
    volumes:
      - ./bot/:/src

  bot:
    volumes:
      - ./bot/:/src
