# Generated by Django 5.1.1 on 2024-09-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_category_task_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'tasks'},
        ),
    ]
