# Generated by Django 5.1.1 on 2024-09-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
