# Generated by Django 5.1.1 on 2024-09-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tag_options_alter_tag_table'),
        ('tasks', '0004_alter_task_options_alter_task_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tags.tag'),
        ),
    ]
