# Generated by Django 5.1.1 on 2024-09-09 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_tags'),
        ('users', '0004_alter_telegramuser_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='telegram_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.telegramuser'),
        ),
    ]
