# Generated by Django 5.2.6 on 2025-09-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tag_options_alter_tag_table'),
        ('tasks', '0006_alter_task_telegram_user'),
        ('users', '0006_alter_telegramuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_enqueued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='notify_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='notify_status',
            field=models.CharField(choices=[('pending', 'pending'), ('enqueued', 'enqueued'), ('sent', 'sent'), ('failed', 'failed')], default='pending', max_length=16),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['notify_status', 'remind_time'], name='tasks_notify__5a6d6c_idx'),
        ),
    ]
