# Generated by Django 5.1.1 on 2024-09-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
    ]
