# Generated by Django 5.1.1 on 2024-09-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_telegramuser_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='telegramuser',
            table='telegram_users',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
