# Generated by Django 5.1.1 on 2024-09-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_telegramuser_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(blank=True, default='ru', max_length=2, null=True),
        ),
    ]
