# Generated by Django 5.2.6 on 2025-09-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_telegramuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
